const STUDENTS =[ 
{key:  'key1',
name: 'Абдуллина Лейла',
score: 'score1'},
{name:'Акопян Диана',
key:  'key2',
score: 'score2'},
{name:'Белых Георгий',
key:  'key3',
score: 'score3'},
{name:'Головкина Ольга',
key:  'key4',
score: 'score4'},
{name:'Денисенко Максим',
key:  'key5',
score: 'score5'},
{name:'Евстратова Вероника',
key:  'key6',
score: 'score6'},
{name:'Жадёнова Ксения',
key:  'key7',
score: 'score7'},
{name:'Злобина Варвара',
key:  'key8',
score: 'score8'},
{name:'Климова Нина',
key:  'key9',
score: 'score9'},
{name:'Коваленко Анна',
key:  'key10',
score: 'score10'},
{name:'Крейнин Даниил',
key:  'key11',
score: 'score11'},
{name:'Кудрявцев Артем',
key:  'key12',
score: 'score12'},
{name:'Лапенков Александр',
key:  'key13',
score: 'score13'},
{name:'Лебедева Елизавета',
key:  'key14',
score: 'score14'},
{name:'Макалкина Алёна',
key:  'key15',
score: 'score15'},
{name:'Макеев Илья',
key:  'key16',
score: 'score16'},
{name:'Маликова Анна',
key:  'key17',
score: 'score17'},
{name:'Миронова Екатерина',
key:  'key18',
score: 'score18'},
{name:'Моро Илья',
key:  'key19',
score: 'score19'},
{name:'Небольсина Екатерина',
key:  'key20',
score: 'score20'},
{name:'Осипян Владимир',
key:  'key21',
score: 'score21'},
{name:'Ответчиков Илья',
key:  'key22',
score: 'score22'},
{name: 'Панин Денис',
key:  'key23',
score: 'score23'},
{name: 'Подлесных Антон',
key:  'key24',
score: 'score24'},
{name: 'Проничев Вадим',
key:  'key25',
score: 'score25'},
{name: 'Пучкова Ефросинья',
key:  'key26',
score: 'score26'},
{name: 'Синицкий Максим',
key:  'key27',
score: 'score27'},
{name: 'Соколова София',
key:  'key28',
score: 'score28'},
{name: 'Сочилина Александра',
key:  'key29',
score: 'score29'},
{name: 'Стрельченко София',
key:  'key30',
score: 'score30'},
{name: 'Трусов Георгий',
key:  'key31',
score: 'score31'},
{name: 'Харитонова Елизавета',
key:  'key32',
score: 'score32'},
{name: 'Шаршуков Иван',
key:  'key33',
score: 'score33'},
{name: 'Юрков Давид',
key:  'key34',
score: 'score34'}
];


const result = document.getElementById('points');
const login = document.getElementById('login');

let content='';
STUDENTS.forEach ((element) =>{
content += `<div class="res"><p>${element.name}</p> <p class="sc">${localStorage.getItem(element.score)}</p></div>`;})

login.innerHTML = content;


         